// File automatically generated by haxe_maker. Don't modify.

class I18nData {
  public static function en():Array<String> {
    return [
      "Accept = Accept",
      "Cancel = Cancel",
      "Cash = Cash",
      "Change language to = Change language to",
      "Change password = Change password",
      "Change Password = Change Password",
      "Check gray squares = Check gray squares",
      "Click %0 to continue. = Click %0 to continue.",
      "Confirm password = Confirm password",
      "Confirm password is missing = 'Confirm password' is missing",
      "Current password = Current password",
      "Current password is missing = 'Current password' is missing",
      "Fail trying to change password = Fail trying to change password",
      "Grey squares checks are wrong = Grey squares checks are wrong",
      "here = here",
      "Keep connected = Keep connected",
      "Login = Login",
      "Logout-message = <p>%0 has finished.</p><p><b>Good by!</b></p>",
      "New password = New password",
      "New password is missing = 'New password' is missing",
      "Password = Password",
      "Password and Confirm password do not match = Password and Confirm password do not match",
      "Password is missing = Password is missing",
      "Password successfully changed = Password successfully changed",
      "Plan = Plan",
      "Session is expired. = Session is expired.",
      "Settings = Settings",
      "User = User",
      "User name is missing = User name is missing",
      "Wrong password = Wrong password",
      ""];
  }

  public static function es():Array<String> {
    return [
      "Accept = Aceptar",
      "Cancel = Cancelar",
      "Cash = Caja",
      "Change language to = Cambiar lenguaje a",
      "Change password = Cambiar contraseña",
      "Change Password = Cambiar la contraseña",
      "Check gray squares = Marcar los cuadrados grises",
      "Click %0 to continue. = Hacer click %0 para continuar.",
      "Confirm password = Confirmar la contraseña",
      "Confirm password is missing = Falta la confirmación de la contraseña",
      "Current password = Contraseña actual",
      "Current password is missing = Falta por indicar la contraseña actual",
      "Fail trying to change password = Fallo intentando cambiar la contraseña",
      "Grey squares checks are wrong = Las casillas grises están mal marcadas",
      "here = aquí",
      "Keep connected = Mantenerse conectado",
      "Login = Identificación",
      "Logout-message = <p>%0 ha terminado.</p><p><b>¡Hasta pronto!</b></p>",
      "New password = Nueva contraseña",
      "New password is missing = Falta por indicar la nueva contraseña",
      "Password = Contraseña",
      "Password and Confirm password do not match = La contraseña y su confirmación no coinciden",
      "Password is missing = Falta por indicar la contraseña",
      "Password successfully changed = La contraseña se cambió adecuadamente",
      "Plan = Plan",
      "Session is expired. = La sesión ha expirado.",
      "Settings = Configuración",
      "User = Usuario",
      "User name is missing = Falta por indicar el nombre del usuario",
      "Wrong password = La contraseña es incorrecta",
      ""];
  }

}
