// File automatically generated by haxe_maker. Don't modify.

class I18nData {
  public static function en():Array<String> {
    return [
      "Accept = Accept",
      "Cash = Cash",
      "Check gray squares = Check gray squares",
      "Click %0 to continue. = Click %0 to continue.",
      "Grey squares checks are wrong = Grey squares checks are wrong",
      "here = here",
      "Keep connected = Keep connected",
      "Login = Login",
      "Logout-message = <p>%0 has finished.</p><p><b>Good by!</b></p>",
      "Password = Password",
      "Password is missing = Password is missing",
      "Plan = Plan",
      "Session is expired. = Session is expired.",
      "Settings = Settings",
      "User = User",
      "User name is missing = User name is missing",
      "Wrong password = Wrong password",
      ""];
  }

  public static function es():Array<String> {
    return [
      "Accept = Aceptar",
      "Cash = Caja",
      "Check gray squares = Marcar los cuadrados grises",
      "Click %0 to continue. = Hacer click %0 para continuar.",
      "Grey squares checks are wrong = Las casillas grises están mal marcadas",
      "here = aquí",
      "Keep connected = Mantenerse conectado",
      "Login = Identificación",
      "Logout-message = <p>%0 ha terminado.</p><p><b>¡Hasta pronto!</b></p>",
      "Password = Contraseña",
      "Password is missing = Falta por indicar la contraseña",
      "Plan = Plan",
      "Session is expired. = La sesión ha expirado.",
      "Settings = Configuración",
      "User = Usuario",
      "User name is missing = Falta por indicar el nombre del usuario",
      "Wrong password = La contraseña es incorrecta",
      ""];
  }

}
