// File automatically generated by haxe_maker. Don't modify.

class I18nData {
  public static function en():Array<String> {
    return [
      "Coordinates = Coordinates",
      "Download = Download",
      "Draw = Draw",
      "File name = File name",
      "Language = Language",
      "Load Functions = Load Functions",
      "Off = Off",
      "On = On",
      "Only can be uploaded one file = Only can be uploaded one file",
      "Precode = Precode",
      "Preview = Preview",
      "Save Functions = Save Functions",
      ""];
  }

  public static function es():Array<String> {
    return [
      "Coordinates = Coordenadas",
      "Download = Descargar",
      "Draw = Dibujar",
      "File name = Nombre del archivo",
      "Language = Lenguaje",
      "Load Functions = Cargar Funciones",
      "Off = Off",
      "On = On",
      "Only can be uploaded one file = Solo se puede subir un arhivo",
      "Precode = Precódigo",
      "Preview = Vista Previa",
      "Save Functions = Guardar funciones",
      ""];
  }

}
