// File automatically generated by haxe_maker. Don't modify.

class I18nData {
  public static function en():Array<String> {
    return [
      ""];
  }

  public static function es():Array<String> {
    return [
      ""];
  }

}
