// File automatically generated by haxe_maker. Don't modify.

class I18nData {
  public static function en():String {
    return "" +
      "Change Language to %0 = Cambiar el idioma a %0\n" +
      "Delete %0? = Delete %0?\n" +
      "Libraries = Libraries\n" +
      "Name '%0' contains '%1' = Name '%0' contains '%1'\n" +
      "Name '%0' contains blanks = Name '%0' contains blanks\n" +
      "Name '%0' is repeated = Name '%0' is repeated\n" +
      "Name is missing = Name is missing\n" +
      "Path can not end with '/' = Path can not end with '/'\n" +
      "Path is missing = Path is missing\n" +
      "There are no libraries = There are no libraries\n" +
      "This source can not be selected, because it does not exist = This source can not be selected, because it does not exist\n" +
      "";
  }

  public static function es():String {
    return "" +
      "Change Language to %0 = Change Language to %0\n" +
      "Delete %0? = ¿Eliminar %0?\n" +
      "Libraries = Librerías\n" +
      "Name '%0' contains '%1' = El nombre '%0' contiene '%1'\n" +
      "Name '%0' contains blanks = El nombre '%0' contiene espacios en blanco\n" +
      "Name '%0' is repeated = El nombre está repetido\n" +
      "Name is missing = Falta el nombre\n" +
      "Path can not end with '/' = La ruta no puede terminar con '/'\n" +
      "Path is missing = Falta la ruta\n" +
      "There are no libraries = No hay librerías\n" +
      "This source can not be selected, because it does not exist = Esta fuente no puede ser seleccionada por que no existe\n" +
      "";
  }

}
