// File automatically generated by haxe_maker. Don't modify.

class I18nData {
  public static function en():String {
    return "" +
      "";
  }

  public static function es():String {
    return "" +
      "here = aquí\n" +
      "";
  }

}
