// File automatically generated by haxe_maker. Don't modify.

class I18nData {
  public static function en():Array<String> {
    return [
      "<br>View-mkEndMenu.%0%1%2<br> = <br>Congratulations!!!<br>Sudoku successfully solved in<br>%0h, %1m and %2s.<br><br>",
      "Accept = Accept",
      "Cancel = Cancel",
      "Change language = Change language",
      "Change to pen = Change to pen",
      "Change to pencil = Change to pencil",
      "Clear all = Clear all",
      "Clear all.\nContinue? = Clear all.\nContinue?",
      "Clear pencil = Clear pencil",
      "Clear pencil.\nContinue? = Clear pencil.\nContinue?",
      "Continue = Continue",
      "Copy = Copy",
      "Copy external sudoku = Copy an external sudoku",
      "Down level = Down level",
      "New = New",
      "New sudoku = New sudoku",
      "Open = Load",
      "Open sudoku = Load sudoku",
      "Save = Save",
      "Search mistakes = Search mistakes",
      "Solve = Solve",
      "Solve sudoku.\nContinue? = Solve sudoku.\nContinue?",
      "Solved sudoku = Solved sudoku",
      "Sudoku has %0 numbers and the (minimun-maximun) allowed is (25-50) = Sudoku has %0 numbers and the (minimun-maximun) allowed is (25-50)",
      "Sudoku has been saved = Sudoku has been saved",
      "Sudoku has more than one solution.\nContinue? = Sudoku has more than one solution.\nContinue?",
      "Sudoku has no sulution = Sudoku has no sulution",
      "There are %0 errors in data = There are %0 errors in data",
      "Up level = Up level",
      "Without records = Without records",
      ""];
  }

  public static function es():Array<String> {
    return [
      "<br>View-mkEndMenu.%0%1%2<br> = <br>¡¡¡Felicidades!!!<br>Sudoku correctamente resuelto en<br>%0h, %1m y %2s.<br><br>",
      "Accept = Aceptar",
      "Cancel = Cancelar",
      "Change language = Cambiar el lenguaje",
      "Change to pen = Cambiar a bolígrafo",
      "Change to pencil = Cambiar a lápiz",
      "Clear all = Limpiar todo",
      "Clear all.\nContinue? = Limplar todo.\n¿Continuar?",
      "Clear pencil = Borrar el lapiz",
      "Clear pencil.\nContinue? = Borrar el lápiz.\n¿Continuar?",
      "Continue = Continuar",
      "Copy = Copiar",
      "Copy external sudoku = Copiar un sudoku externo",
      "Down level = Bajar un nivel",
      "New = Nuevo",
      "New sudoku = Nuevo sudoku",
      "Open = Recuperar",
      "Open sudoku = Recuperar sudoku",
      "Save = Guardar",
      "Search mistakes = Buscar errores",
      "Solve = Soluccionar",
      "Solve sudoku.\nContinue? = Soluccionar el sudoku.\n¿Continuar?",
      "Solved sudoku = Sudoky resuelto",
      "Sudoku has %0 numbers and the (minimun-maximun) allowed is (25-50) = El sudoku tiene %0 números y el (mínimo-máximo) permitido es (25-50)",
      "Sudoku has been saved = El sudoku ha sido guardado",
      "Sudoku has more than one solution.\nContinue? = El sudoku tiene más de una solucción.\n¿Continuar?",
      "Sudoku has no sulution = El sudoku no tiene solución",
      "There are %0 errors in data = Hay %0 errores en los datos",
      "Up level = Subir un nivel",
      "Without records = Sin registros",
      ""];
  }

}
