// File automatically generated by GalleryGenerator.hx.
// DON'T MODIFY.

package view;

class GalleryAux{
  public static function getData():Map<String, Array<String>> {
    var r = new Map<String, Array<String>>();
    r.set("HenonAttractor", [
      "egg-0",
      "egg-1",
      "margin-0",
      "margin-1",
      "O-0",
      "O-1",
      "sin-0",
      "sin-1",
      "tubular-0",
      "tubular-1",
      "waves-0",
      "waves-1"
    ]);
    r.set("MultiscrollAttractor-1", [
      "belt-0",
      "belt-1",
      "cirrus",
      "crossedBars-0",
      "flyingStains",
      "handcuff-0",
      "handcuff-1",
      "minimalCross-0",
      "minimalCross-1",
      "minimalCross-2",
      "motherboard-0",
      "motherboard-1",
      "motherboard-2",
      "motherboard-3",
      "motherboard-4",
      "semiface"
    ]);
    return r;
  }
}
